let currentLang = 'en';

export function setLang(lang) {
  currentLang = lang;
}

export function getMessage(key) {
  return messages[key][currentLang];
}

export function getDisplayName(name) {
  return currentLang === 'ja' ? (translations[name] || name) : name;
}

export function getRegionDisplayName(region) {
  if (currentLang === 'ja') return regionNameJa[region] || region;
  return region;
}

export function updateButtonTexts(lang) {
  document.querySelectorAll('[data-en][data-ja]').forEach(el => {
    const text = lang === 'ja' ? el.dataset.ja : el.dataset.en;
    if (el.tagName === 'INPUT') el.placeholder = text;
    else el.textContent = text;
  });
}

// ==================

const messages = {
  noViewSettings: { en: 'has no view settings', ja: 'のビュー設定がありません' },
};

const regionNameJa = {
  'Europe': 'ヨーロッパ',
  'Africa': 'アフリカ',
  'Middle East': '中東',
  'Asia': 'アジア',
  'Oceania': 'オセアニア',
  'North America': '北アメリカ',
  'South America': '南アメリカ',
  'Antarctica': '南極大陸',
  'Default': '未定義',
  'USA States': 'アメリカ(州)',
  'China Provinces': '中国(省)',
  'Japan Prefectures': '日本(都道府県)',
  'Commands': 'コマンド',
};

const translations = {
  "README": "わたしを読んで",
  "Lat: ": "緯度: ",
  "Lng: ": "経度: ",
  "International Date Line": "国際日付変更線",
  "Albania": "アルバニア",
  "Andorra": "アンドラ",
  "Armenia": "アルメニア",
  "Austria": "オーストリア",
  "Azerbaijan": "アゼルバイジャン",
  "Belarus": "ベラルーシ",
  "Belgium": "ベルギー",
  "Bosnia and Herzegovina": "ボスニア・ヘルツェゴビナ",
  "Bulgaria": "ブルガリア",
  "Croatia": "クロアチア",
  "Cyprus": "キプロス",
  "Czechia": "チェコ",
  "Denmark": "デンマーク",
  "Estonia": "エストニア",
  "Finland": "フィンランド",
  "France": "フランス",
  "Georgia": "ジョージア",
  "Germany": "ドイツ",
  "Greece": "ギリシャ",
  "Hungary": "ハンガリー",
  "Iceland": "アイスランド",
  "Ireland": "アイルランド",
  "Italy": "イタリア",
  "Kosovo": "コソボ",
  "Latvia": "ラトビア",
  "Liechtenstein": "リヒテンシュタイン",
  "Lithuania": "リトアニア",
  "Luxembourg": "ルクセンブルク",
  "Malta": "マルタ",
  "Moldova": "モルドバ",
  "Monaco": "モナコ",
  "Montenegro": "モンテネグロ",
  "Netherlands": "オランダ",
  "North Macedonia": "北マケドニア",
  "Norway": "ノルウェー",
  "Poland": "ポーランド",
  "Portugal": "ポルトガル",
  "Republic of Serbia": "セルビア",
  "Romania": "ルーマニア",
  "Russia": "ロシア",
  "San Marino": "サンマリノ",
  "Slovakia": "スロバキア",
  "Slovenia": "スロベニア",
  "Spain": "スペイン",
  "Sweden": "スウェーデン",
  "Switzerland": "スイス",
  "Ukraine": "ウクライナ",
  "United Kingdom": "イギリス",
  "Vatican": "バチカン",
  "Algeria": "アルジェリア",
  "Angola": "アンゴラ",
  "Benin": "ベナン",
  "Botswana": "ボツワナ",
  "Burkina Faso": "ブルキナファソ",
  "Burundi": "ブルンジ",
  "Cabo Verde": "カーボベルデ",
  "Cameroon": "カメルーン",
  "Central African Republic": "中央アフリカ共和国",
  "Chad": "チャド",
  "Comoros": "コモロ",
  "Democratic Republic of the Congo": "コンゴ民主共和国",
  "Djibouti": "ジブチ",
  "Egypt": "エジプト",
  "Equatorial Guinea": "赤道ギニア",
  "Eritrea": "エリトリア",
  "eSwatini": "エスワティニ",
  "Ethiopia": "エチオピア",
  "Gabon": "ガボン",
  "Gambia": "ガンビア",
  "Ghana": "ガーナ",
  "Guinea": "ギニア",
  "Guinea-Bissau": "ギニアビサウ",
  "Ivory Coast": "コートジボワール",
  "Kenya": "ケニア",
  "Lesotho": "レソト",
  "Liberia": "リベリア",
  "Libya": "リビア",
  "Madagascar": "マダガスカル",
  "Malawi": "マラウイ",
  "Mali": "マリ",
  "Mauritania": "モーリタニア",
  "Mauritius": "モーリシャス",
  "Morocco": "モロッコ",
  "Mozambique": "モザンビーク",
  "Namibia": "ナミビア",
  "Niger": "ニジェール",
  "Nigeria": "ナイジェリア",
  "Republic of the Congo": "コンゴ共和国",
  "Rwanda": "ルワンダ",
  "São Tomé and Principe": "サントメ・プリンシペ",
  "Senegal": "セネガル",
  "Seychelles": "セーシェル",
  "Sierra Leone": "シエラレオネ",
  "Somalia": "ソマリア",
  "South Africa": "南アフリカ",
  "South Sudan": "南スーダン",
  "Sudan": "スーダン",
  "Togo": "トーゴ",
  "Tunisia": "チュニジア",
  "Uganda": "ウガンダ",
  "United Republic of Tanzania": "タンザニア",
  "Western Sahara": "西サハラ",
  "Zambia": "ザンビア",
  "Zimbabwe": "ジンバブエ",
  "Afghanistan": "アフガニスタン",
  "Bahrain": "バーレーン",
  "Iran": "イラン",
  "Iraq": "イラク",
  "Israel": "イスラエル",
  "Jordan": "ヨルダン",
  "Kuwait": "クウェート",
  "Lebanon": "レバノン",
  "Oman": "オマーン",
  "Palestine": "パレスチナ",
  "Qatar": "カタール",
  "Saudi Arabia": "サウジアラビア",
  "Syria": "シリア",
  "Turkey": "トルコ",
  "United Arab Emirates": "アラブ首長国連邦",
  "Yemen": "イエメン",
  "Bangladesh": "バングラデシュ",
  "Bhutan": "ブータン",
  "Brunei": "ブルネイ",
  "Cambodia": "カンボジア",
  "China": "中国",
  "East Timor": "東ティモール",
  "Hong Kong S.A.R.": "香港特別行政区",
  "India": "インド",
  "Indonesia": "インドネシア",
  "Japan": "日本",
  "Kazakhstan": "カザフスタン",
  "Kyrgyzstan": "キルギス",
  "Laos": "ラオス",
  "Macao S.A.R": "マカオ特別行政区",
  "Malaysia": "マレーシア",
  "Maldives": "モルディブ",
  "Mongolia": "モンゴル",
  "Myanmar": "ミャンマー",
  "Nepal": "ネパール",
  "North Korea": "北朝鮮",
  "Pakistan": "パキスタン",
  "Philippines": "フィリピン",
  "Singapore": "シンガポール",
  "South Korea": "韓国",
  "Sri Lanka": "スリランカ",
  "Taiwan": "台湾",
  "Tajikistan": "タジキスタン",
  "Thailand": "タイ",
  "Turkmenistan": "トルクメニスタン",
  "Uzbekistan": "ウズベキスタン",
  "Vietnam": "ベトナム",
  "Australia": "オーストラリア",
  "Cook Islands": "クック諸島",
  "Federated States of Micronesia": "ミクロネシア連邦",
  "Fiji": "フィジー",
  "Kiribati": "キリバス",
  "Marshall Islands": "マーシャル諸島",
  "Nauru": "ナウル",
  "New Caledonia": "ニューカレドニア",
  "New Zealand": "ニュージーランド",
  "Niue": "ニウエ",
  "Palau": "パラオ",
  "Papua New Guinea": "パプアニューギニア",
  "Samoa": "サモア",
  "Solomon Islands": "ソロモン諸島",
  "Tonga": "トンガ",
  "Tuvalu": "ツバル",
  "Vanuatu": "バヌアツ",
  "Antigua and Barbuda": "アンティグア・バーブーダ",
  "Barbados": "バルバドス",
  "Belize": "ベリーズ",
  "Bermuda": "バミューダ諸島",
  "Canada": "カナダ",
  "Costa Rica": "コスタリカ",
  "Cuba": "キューバ",
  "Dominica": "ドミニカ国",
  "Dominican Republic": "ドミニカ共和国",
  "El Salvador": "エルサルバドル",
  "Grenada": "グレナダ",
  "Greenland": "グリーンランド",
  "Guatemala": "グアテマラ",
  "Haiti": "ハイチ",
  "Honduras": "ホンジュラス",
  "Jamaica": "ジャマイカ",
  "Mexico": "メキシコ",
  "Nicaragua": "ニカラグア",
  "Panama": "パナマ",
  "Puerto Rico": "プエルトリコ",
  "Saint Kitts and Nevis": "セントクリストファー・ネーヴィス",
  "Saint Lucia": "セントルシア",
  "Saint Vincent and the Grenadines": "セントビンセントおよびグレナディーン諸島",
  "The Bahamas": "バハマ",
  "Trinidad and Tobago": "トリニダード・トバゴ",
  "United States of America": "アメリカ合衆国",
  "Argentina": "アルゼンチン",
  "Bolivia": "ボリビア",
  "Brazil": "ブラジル",
  "Chile": "チリ",
  "Colombia": "コロンビア",
  "Ecuador": "エクアドル",
  "Guyana": "ガイアナ",
  "Paraguay": "パラグアイ",
  "Peru": "ペルー",
  "Suriname": "スリナム",
  "Uruguay": "ウルグアイ",
  "Venezuela": "ベネズエラ",
  "Antarctica": "南極大陸",
  /* アメリカ */
  "Pennsylvania": "ペンシルベニア",
  "New Jersey": "ニュージャージー",
  "Connecticut": "コネチカット",
  "Massachusetts": "マサチューセッツ",
  "Delaware": "デラウェア",
  "Maryland": "メリーランド",
  "South Carolina": "サウスカロライナ",
  "New Hampshire": "ニューハンプシャー",
  "Virginia": "バージニア",
  "New York": "ニューヨーク",
  "North Carolina": "ノースカロライナ",
  "Rhode Island": "ロードアイランド",
  "Vermont": "バーモント",
  "Kentucky": "ケンタッキー",
  "Tennessee": "テネシー",
  "Ohio": "オハイオ",
  "Louisiana": "ルイジアナ",
  "Indiana": "インディアナ",
  "Mississippi": "ミシシッピ",
  "Illinois": "イリノイ",
  "Alabama": "アラバマ",
  "Maine": "メイン",
  "Missouri": "ミズーリ",
  "Arkansas": "アーカンソー",
  "Michigan": "ミシガン",
  "Florida": "フロリダ",
  "Texas": "テキサス",
  "Iowa": "アイオワ",
  "Wisconsin": "ウィスコンシン",
  "California": "カリフォルニア",
  "Minnesota": "ミネソタ",
  "Oregon": "オレゴン",
  "Kansas": "カンザス",
  "West Virginia": "ウェストバージニア",
  "Nevada": "ネバダ",
  "Nebraska": "ネブラスカ",
  "Colorado": "コロラド",
  "North Dakota": "ノースダコタ",
  "South Dakota": "サウスダコタ",
  "Montana": "モンタナ",
  "Washington": "ワシントン",
  "Idaho": "アイダホ",
  "Wyoming": "ワイオミング",
  "Utah": "ユタ",
  "Oklahoma": "オクラホマ",
  "New Mexico": "ニューメキシコ",
  "Arizona": "アリゾナ",
  "Alaska": "アラスカ",
  "Hawaii": "ハワイ",
  "District of Columbia": "ワシントンD.C.",
  /* 中国 */
  "Xinjiang": "新疆",
  "Xizang": "チベット",
  "Inner Mongol": "内モンゴル",
  "Gansu": "甘粛",
  "Yunnan": "雲南",
  "Heilongjiang": "黒竜江",
  "Jilin": "吉林",
  "Liaoning": "遼寧",
  "Guangxi": "広西",
  "Guangdong": "広東",
  "Hainan": "海南",
  "Fujian": "福建",
  "Zhejiang": "浙江",
  "Shanghai": "上海",
  "Jiangsu": "江蘇",
  "Shandong": "山東",
  "Hebei": "河北",
  "Tianjin": "天津",
  "Paracel Islands": "西沙諸島",
  "Beijing": "北京",
  "Sichuan": "四川",
  "Chongqing": "重慶",
  "Guizhou": "貴州",
  "Hunan": "湖南",
  "Ningxia": "寧夏",
  "Shaanxi": "陝西",
  "Qinghai": "青海",
  "Shanxi": "山西",
  "Jiangxi": "江西",
  "Henan": "河南",
  "Hubei": "湖北",
  "Anhui": "安徽",
  /* 日本 */
  "Hokkaidō": "北海道",
  "Aomori": "青森",
  "Iwate": "岩手",
  "Miyagi": "宮城",
  "Akita": "秋田",
  "Yamagata": "山形",
  "Fukushima": "福島",
  "Ibaraki": "茨城",
  "Tochigi": "栃木",
  "Gunma": "群馬",
  "Saitama": "埼玉",
  "Chiba": "千葉",
  "Tokyo": "東京",
  "Kanagawa": "神奈川",
  "Niigata": "新潟",
  "Toyama": "富山",
  "Ishikawa": "石川",
  "Fukui": "福井",
  "Yamanashi": "山梨",
  "Nagano": "長野",
  "Gifu": "岐阜",
  "Shizuoka": "静岡",
  "Aichi": "愛知",
  "Mie": "三重",
  "Shiga": "滋賀",
  "Kyōto": "京都",
  "Ōsaka": "大阪",
  "Hyōgo": "兵庫",
  "Nara": "奈良",
  "Wakayama": "和歌山",
  "Tottori": "鳥取",
  "Shimane": "島根",
  "Okayama": "岡山",
  "Hiroshima": "広島",
  "Yamaguchi": "山口",
  "Tokushima": "徳島",
  "Kagawa": "香川",
  "Ehime": "愛媛",
  "Kōchi": "高知",
  "Fukuoka": "福岡",
  "Saga": "佐賀",
  "Nagasaki": "長崎",
  "Kumamoto": "熊本",
  "Ōita": "大分",
  "Miyazaki": "宮崎",
  "Kagoshima": "鹿児島",
  "Okinawa": "沖縄",
};
